steps:
  # build rust-api-server
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-rust-api-server'
    args:
      - 'build'
      - '-t'
      - 'us.gcr.io/${PROJECT_NAME}/rust-api-server:latest'
      - '-t'
      - 'us.gcr.io/${PROJECT_NAME}/rust-api-server:$BRANCH_NAME-$REVISION_ID'
      - '--build-arg'
      - 'DIR_NAME=rust-api-server'
      - '--cache-from'
      - 'us.gcr.io/${PROJECT_NAME}/rust-api-server:latest'
      - 'rust-api-server'
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-mongodb'
    args:
      - 'build'
      - '-t'
      - 'us.gcr.io/${PROJECT_NAME}/mongodb:latest'
      - '-t'
      - 'us.gcr.io/${PROJECT_NAME}/mongodb:$BRANCH_NAME-$REVISION_ID'
      - '--cache-from'
      - 'us.gcr.io/${PROJECT_NAME}/mongodb:latest'
      - 'mongodb'
    waitFor:
      - '-'
images:
  - 'us.gcr.io/${PROJECT_NAME}/mongodb:latest'
  - 'us.gcr.io/${PROJECT_NAME}/mongodb:$BRANCH_NAME-$REVISION_ID'
  - 'us.gcr.io/${PROJECT_NAME}/rust-api-server:latest'
  - 'us.gcr.io/${PROJECT_NAME}/rust-api-server:$BRANCH_NAME-$REVISION_ID'
