steps:
  # build rust-api-server
  - name: 'gcr.io/kaniko-project/executor:latest'
    id: 'build-rust-api-server'
    args:
      - '--dockerfile=rust-api-server/Dockerfile'
      - '--context=dir://rust-api-server'
      - '--destination=us.gcr.io/${PROJECT_ID}/rust-api-server:latest'
      - '--build-arg DIR_NAME=rust-api-server'
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-mongodb'
    args:
      - 'build'
      - '-t'
      - 'us.gcr.io/${PROJECT_ID}/mongodb:latest'
      - '-t'
      - 'us.gcr.io/${PROJECT_ID}/mongodb:$BRANCH_NAME-$REVISION_ID'
      - '--cache-from'
      - 'us.gcr.io/${PROJECT_ID}/mongodb:latest'
      - 'mongodb'
    waitFor:
      - '-'
images:
  - 'us.gcr.io/${PROJECT_ID}/mongodb:latest'
  - 'us.gcr.io/${PROJECT_ID}/mongodb:$BRANCH_NAME-$REVISION_ID'
  - 'us.gcr.io/${PROJECT_ID}/rust-api-server:latest'
  - 'us.gcr.io/${PROJECT_ID}/rust-api-server:$BRANCH_NAME-$REVISION_ID'
