steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'pull-app-builder'
    args:
      - 'pull'
      - 'us.gcr.io/${PROJECT_ID}/rust_api_server:build-stage-cache'
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'pull-app'
    args:
      - 'pull'
      - 'us.gcr.io/${PROJECT_ID}/rust_api_server:latest'
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'pull-db'
    args:
      - 'pull'
      - 'us.gcr.io/${PROJECT_ID}/mongodb:latest'
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-app-builder'
    args:
      - 'build'
      - '-t'
      - 'us.gcr.io/${PROJECT_ID}/rust_api_server:build-stage-cache'
      - '--target'
      - 'builder'
      - '--cache-from'
      - 'us.gcr.io/${PROJECT_ID}/rust_api_server:build-stage-cache'
      - '--build-arg'
      - 'DIR_NAME=rust_api_server'
      - 'rust_api_server'
    waitFor: ['pull-app-builder', 'pull-app']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-app'
    args:
      - 'build'
      - '-t'
      - 'us.gcr.io/${PROJECT_ID}/rust_api_server:latest'
      - '-t'
      - 'us.gcr.io/${PROJECT_ID}/rust_api_server:$BRANCH_NAME-$REVISION_ID'
      - '--cache-from'
      - 'us.gcr.io/${PROJECT_ID}/rust_api_server:latest'
      - '--cache-from'
      - 'us.gcr.io/${PROJECT_ID}/rust_api_server:build-stage-cache'
      - '--build-arg'
      - 'DIR_NAME=rust_api_server'
      - 'rust_api_server'
    waitFor: ['build-app-builder']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-mongodb'
    args:
      - 'build'
      - '-t'
      - 'us.gcr.io/${PROJECT_ID}/mongodb:latest'
      - '-t'
      - 'us.gcr.io/${PROJECT_ID}/mongodb:$BRANCH_NAME-$REVISION_ID'
      - '--cache-from'
      - 'us.gcr.io/${PROJECT_ID}/mongodb:latest'
      - 'mongodb'
    waitFor: ['pull-db']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'get-credentials'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'rocket-practice-cluster'
      - '--zone=${_ZONE}'
      - '--project=${PROJECT_ID}'
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'deployment-default'
    args:
      - 'apply'
      - '-f'
      - 'k8s/default'
      - '--record'
    waitFor: ['build-app', 'build-mongodb', 'get-credentials']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'decrypto-deployment-production-loadbalancer'
    args:
      - 'kms'
      - 'decrypt'
      - '--location'
      - 'global'
      - '--keyring'
      - 'rust-api'
      - '--key'
      - 'kubernetes-deployment-key'
      - '--ciphertext-file'
      - 'k8s/production/loadbalancer.yaml.encode'
      - '--plaintext-file'
      - 'k8s/production/loadbalancer.yaml'
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'deployment-production-loadbalancer'
    args:
      - 'apply'
      - '-f'
      - 'k8s/production/loadbalancer.yaml'
      - '--record'
    waitFor: ['deployment-production-loadbalancer', 'build-app', 'build-mongodb', 'get-credentials']

timeout: 3600s
images:
  - 'us.gcr.io/${PROJECT_ID}/mongodb:latest'
  - 'us.gcr.io/${PROJECT_ID}/mongodb:$BRANCH_NAME-$REVISION_ID'
  - 'us.gcr.io/${PROJECT_ID}/rust_api_server:latest'
  - 'us.gcr.io/${PROJECT_ID}/rust_api_server:$BRANCH_NAME-$REVISION_ID'
  - 'us.gcr.io/${PROJECT_ID}/rust_api_server:build-stage-cache'
# todo:
# pod -> deployment
