apiVersion: v1
kind: Pod
metadata:
  name: web-server-pod
  labels:
    app: web-server
spec:
  restartPolicy: Never
  containers:
    - name: rocket-container
      image: us.gcr.io/cloud-shell-gcloud/rocket-server
      ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Pod
metadata:
  name: mongodb-pod
  labels:
    app: mongodb
spec:
  restartPolicy: Never
  containers:
    - name: mongodb-container
      image: us.gcr.io/cloud-shell-gcloud/mongodb
      ports:
        - containerPort: 27017
