apiVersion: v1
kind: Service
metadata:
  name: web-server-service
spec:
  type: NodePort
  ports:
    - name: "http-port"
      protocol: "TCP"
      targetPort: 8000
      port: 8000
  selector:
    app: web-server

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  type: NodePort
  ports:
    - name: "db-port"
      port: 27017
      targetPort: 27017
  selector:
    app: mongodb