apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
        - name: api-server
          image: us.gcr.io/cloud-shell-gcloud/rust_api_server:production-latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
