apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
spec:
  type: LoadBalancer
  loadBalancerIP: "104.198.14.240"
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 80
      targetPort: 8000
  selector:
    app: web-server