apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  labels:
    app: db
spec:
  restartPolicy: Never
  containers:
    - name: mongodb-container
      image: us.gcr.io/cloud-shell-gcloud/mongodb:production-latest
      ports:
        - containerPort: 27017
