apiVersion: skaffold/v1beta7
kind: Config
build:
  artifacts:
    - image: us.gcr.io/cloud-shell-gcloud/rust-api-server
      context: .
      docker:
        dockerfile: rust-api-server/Dockerfile
    - image: us.gcr.io/cloud-shell-gcloud/mongodb
      docker:
        dockerfile: mongodb/Dockerfile
deploy:
  kubectl:
    manifests:
      # other than production
      - ./k8s/*.yaml
