# do not make sence
apiVersion: skaffold/v1beta7
kind: Config
build:
  artifacts:
    - image: rust_api_server
      context: rust_api_server
      docker:
        dockerfile: Dockerfile
        target: rust_api_server:local-latest
        buildArgs:
          DIR_NAME: rust_api_server
    - image: mongodb
      context: mongodb
      target: mongodb:local-latest
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      # other than production
      - ./k8s/local/*
